### PR TITLE
fix: make behavior identical to git-user-name

### LINKED ISSUE #1: Always returns null

### LINKED ISSUE #3: Does not search global .gitconfig, only local .git/config
(I believe this is a clarification to #1)

This behavior is unexpected, given that `git-user-name` ~~searches both.~~ Edit: actually... it may just search globally?

### PR DESCRIPTION
**Pull request by billiegoose**
Fixes #1 and fixes #3

Did I copy and paste the code from `git-user-name` and replace the word `name` with `email`? Yes. Yes I did.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
@doowb can we merge this? It's one minute to merge, clone and publish.

For me and my flow is even more easier: just merge, everything else is automated :D

**Comment by tunnckoCore** [comment]
@doowb, @jonschlinkert ping pong. :) Just found a reminder comment in my codebase :D

**Comment by anthon** [comment]
Ping, again, @jonschlinkert! Would be lovely to have this merged, so we can remove our own clones. Thanksss!

**Comment by dherault** [comment]
I needed this so I forked the repo, merged this PR and published the package under a different name:
https://www.npmjs.com/package/git-user-email-2

--> `npm install git-user-email-2`

**Pull request merged**
